name: Build and publish

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Extract Project Version
      id: extract_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Find and Upload JAR
      run: |
        # Find the main JAR file (excluding sources and javadoc JARs)
        JAR_FILE=$(find target -type f -name "*.jar" ! -name "*-sources.jar" ! -name "*-javadoc.jar")
        
        # Check if JAR file is found
        if [ -z "$JAR_FILE" ]; then
          echo "No JAR file found"
          exit 1
        fi

        echo "JAR file found: $JAR_FILE"
        
        # Upload JAR file as artifact
        echo "Uploading artifact..."
        mkdir -p artifacts
        cp "$JAR_FILE" artifacts/
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Limbo-${{ env.VERSION }}-${{ github.run_number }}
        path: artifacts/*.jar
